### ISSUE TITLE
Integrate [ spring vault ] for secure secrets management and fix prod startup failure

### ISSUE THREAD

**Issue by Fl1s** [Fl1s/fablewhirl#45]
## \[ Description ]:

Currently, application secrets (Keycloak credentials, Redis URL, Kafka brokers, etc.) are injected via external `.env.prod` files referenced using `spring.config.import`. This works in dev environments but fails in production, as those files are either missing, mislocated, or not properly mounted into pods.

This creates a brittle deployment model — any missing or misconfigured file crashes the app during startup. Moreover, there’s no centralized control, no secret rotation, and it's hard to audit or secure sensitive values(excuse me).

## \[ Problem ]:

* Missing or misconfigured secret files (`.env.prod`) cause apps to fail during deployment.
* Secrets are stored as plain text files — risky and hard to rotate.
* Managing secrets across multiple environments and services is chaotic.
* No centralized visibility or fine-grained access control.
* Leads to fragile, unscalable, and unsafe infrastructure.

## \[ Proposed Solution ]:

Adopt \[Spring Vault] for secure and centralized secrets management using **HashiCorp Vault**:

* Eliminate `.env.prod` files entirely.
* Store all sensitive configuration (credentials, URLs, tokens) in Vault.
* Use `spring.cloud.vault` integration to dynamically pull secrets at runtime based on service identity (via Kubernetes auth or AppRole).
* Separate paths per environment (`secret/dev/...` and `secret/prod/...`).
* Use Vault policies to restrict access to only what each service needs.

### Example replacement for `application-prod.yml`:

```yaml
spring:
  cloud:
    vault:
      uri: ${VAULT.URI}
      authentication: ${VAULT.AUTH}
      kubernetes:
        role: ${VAULT.K8S.ROLE}
        service-account: ${VAULT.K8S.SERVICE_ACCOUNT}
      kv:
        enabled: true
        backend:${VAULT.KV.SECRET}
        application-name: ${SPRING.APPLICATION.NAME}
```

Secrets like this:

```
vault kv put secret/prod/thread-service \
  EUREKA.INSTANCE.HOSTNAME=prod-eureka \
  REDIS.URL=redis://prod-redis:6379 \
  KAFKA.BOOTSTRAP_SERVERS=prod-kafka:9092 \
  KEYCLOAK.REALM=realm \
  ...
```

## \[ Benefits ]:

* Deployment no longer fails due to missing config files.
* No more secrets in source control or CI logs.
* Environment-specific secret isolation.
* Centralized rotation, auditing, access control.
* Scales easily to any number of services and environments.

## \[ Next Steps ]:

* Deploy HashiCorp Vault and configure auth method (Kubernetes preferred).
* Migrate all existing secrets into Vault under structured paths (`secret/dev/...`, `secret/prod/...`).
* Replace `spring.config.import` with Spring Vault integration.
* Create Kubernetes `ServiceAccount`s and roles for each microservice.
* Remove file-based secrets from deployment pipeline and CI/CD.
* Add alerts/logging for secret fetch failures or Vault unavailability.
